<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            'Natal',
            'Mossoró',
            'Parnamirim',
            'São Gonçalo do Amarante',
            'Macaíba',
            'Ceará-Mirim',
            'Extremoz',
            'Caicó',
            'Assú',
            'São José de Mipibu',
            'Currais Novos',
            'Santa Cruz',
            'Apodi',
            'Nova Cruz',
            'João Câmara',
            'Touros',
            'Nísia Floresta',
            'Pau dos Ferros',
            'Canguaretama',
            'Macau',
            'Baraúna',
            'Goianinha',
            'Areia Branca',
            'São Miguel',
            'Monte Alegre',
            'Santo Antônio',
            'Parelhas',
            'Caraúbas',
            'Jucurutu',
            'Tibau do Sul',
            'São Paulo do Potengi',
            'Lagoa Nova',
            'Guamaré',
            'Ipanguaçu',
            'Jardim de Piranhas',
            'Pedro Velho',
            'Alexandria',
            'Upanema',
            'Tangará',
            'Arez',
            'Serra do Mel',
            'Alto do Rodrigues',
            'Santana do Matos',
            'Poço Branco',
            'Pendências',
            'Brejinho (Rio Grande do Norte)',
            'Governador Dix-Sept Rosado',
            'Jardim do Seridó',
            'Angicos',
            'Ielmo Marinho',
            'Montanhas (Rio Grande do Norte)',
            'Taipu',
            'São José do Campestre',
            'Patu',
            'Cerro Corá',
            'Tenente Ananias',
            'Passa-e-Fica',
            'Afonso Bezerra',
            'Vera Cruz',
            'Espírito Santo',
            'Acari',
            'Rio do Fogo',
            'Serra Caiada',
            'Maxaranguape',
            'São Miguel do Gostoso',
            'Campo Redondo',
            'Florânia',
            'Umarizal',
            'São Tomé',
            'Bom Jesus',
            'Grossos',
            'Lajes',
            'Campo Grande',
            'Carnaubais',
            'Pureza',
            'Luís Gomes',
            'Boa Saúde',
            'Baía Formosa',
            'Lagoa Salgada',
            'Martins',
            'Cruzeta',
            'Carnaúba dos Dantas',
            'Marcelino Vieira',
            'Jaçanã',
            'São Rafael',
            'Portalegre',
            'Serra Negra do Norte',
            'Riachuelo',
            'Lagoa de Pedras',
            'Itajá',
            'Doutor Severiano',
            'Lagoa d\'Anta',
            'Antônio Martins',
            'Jandaíra',
            'Serrinha',
            'São Vicente',
            'Caiçara do Norte',
            'Pedro Avelino',
            'Encanto',
            'Senador Elói de Souza',
            'São João do Sabugi',
            'Felipe Guerra',
            'Tenente Laurentino Cruz',
            'José da Penha',
            'São Pedro',
            'Serra de São Bento',
            'Severiano Melo',
            'Rafael Fernandes',
            'Tibau',
            'Equador',
            'Itaú',
            'Várzea',
            'Porto do Mangue',
            'Coronel Ezequiel',
            'Japi',
            'Ouro Branco',
            'Santa Maria',
            'Bento Fernandes',
            'Parazinho',
            'Lajes Pintadas',
            'Janduís',
            'Almino Afonso',
            'Serrinha dos Pintos',
            'Sítio Novo',
            'São José do Seridó',
            'Messias Targino',
            'Rodolfo Fernandes',
            'Coronel João Pessoa',
            'São Francisco do Oeste',
            'Riacho de Santana',
            'Frutuoso Gomes',
            'Senador Georgino Avelino',
            'Barcelona',
            'Paraná',
            'Major Sales',
            'Olho-d\'Água do Borges',
            'São Bento do Trairi',
            'Jundiá',
            'Pedra Grande',
            'Paraú',
            'São Fernando',
            'Lucrécia',
            'Triunfo Potiguar',
            'São Bento do Norte',
            'Caiçara do Rio do Vento',
            'Ruy Barbosa',
            'Vila Flor',
            'Passagem',
            'Venha-Ver',
            'Pilões',
            'Água Nova',
            'Fernando Pedroza',
            'Rafael Godeiro',
            'Riacho da Cruz',
            'Francisco Dantas',
            'Santana do Seridó',
            'Lagoa de Velhos',
            'Pedra Preta',
            'Jardim de Angicos',
            'Timbaúba dos Batistas',
            'Taboleiro Grande',
            'Bodó',
            'Monte das Gameleiras',
            'Galinhos',
            'João Dias',
            'Ipueira',
            'Viçosa',
        ];

        // upsert with $cities array instead of using foreach loop
        foreach ($cities as $city) {
            DB::table('cities')->upsert(['name' => $city], 'id');
        }

        // DB::table('cities')->upsert($cities, 'name');

        // foreach ($cities as $city) {
        //     DB::table('cities')->upsert(['name' => $city], 'name');
        // }
    }
}
